// Generated by https://quicktype.io

export interface PersonalBest {
  place: number;
  run: Run;
  game: Game;
  category: Category;
}

export interface Category {
  data: CategoryData;
}

export interface CategoryData {
  id: string;
  name: string;
  weblink: string;
  type: string;
  rules: string;
  players: Players;
  miscellaneous: boolean;
  links: Link[];
}

export interface Link {
  rel: string;
  uri: string;
}

export interface Players {
  type: string;
  value: number;
}

export interface Game {
  data: GameData;
}

export interface GameData {
  id: string;
  names: Names;
  boostReceived: number;
  boostDistinctDonors: number;
  abbreviation: string;
  weblink: string;
  discord: string;
  released: number;
  "release-date": string;
  ruleset: Ruleset;
  romhack: boolean;
  platforms: Platform[];
  regions: string[];
  moderators: { [key: string]: Moderator };
  created: string;
  assets: { [key: string]: Asset };
  links: Link[];
}

export interface Asset {
  uri: null | string;
}

export enum Moderator {
  Moderator = "moderator",
  SuperModerator = "super-moderator",
}

export interface Names {
  international: string;
  japanese: null;
  twitch: string;
}

export enum Platform {
  Gde32G6K = "gde32g6k",
  The8Gej2N93 = "8gej2n93",
}

export interface Ruleset {
  "show-milliseconds": boolean;
  "require-verification": boolean;
  "require-video": boolean;
  "run-times": string[];
  "default-time": string;
  "emulators-allowed": boolean;
}

export interface Run {
  id: string;
  weblink: string;
  game: string;
  level: null;
  category: string;
  videos: Videos;
  comment: string;
  status: Status;
  players: Player[];
  date: string;
  submitted: string;
  times: Times;
  system: System;
  splits: null;
  values: { [key: string]: string };
  links: Link[];
}

export interface Player {
  rel: string;
  id: string;
  uri: string;
}

export interface Status {
  status: string;
  examiner: string;
  "verify-date": string;
}

export interface System {
  platform: Platform;
  emulated: boolean;
  region: null;
}

export interface Times {
  primary: string;
  primary_t: number;
  realtime: string;
  realtime_t: number;
  realtime_noloads: null;
  realtime_noloads_t: number;
  ingame: null;
  ingame_t: number;
}

export interface Videos {
  links: Asset[];
}
